### ISSUE TITLE
should we use rust-tls instead of open-ssl

### ISSUE THREAD

**Issue by harrydevnull** [AlexPikalov/cdrs#124]
I was thinking of adding windows compilation to cdrs 'appvoyer' but since we need open ssl we have to do customizations on top of base windows image. If instead of using open ssl crate; if we were to use rust tls which is wrapper for OpenSSL on Linux machines and wrapper for native tls implementations in windows and OS X environment it would be natively supported on all platforms. What do you think ?

**Comment by harrydevnull** [comment]
And adding on we might need to add examples on how use private key to do the authentication with the server. The example currently is only using cafile alone; which means we are speaking tls but not doing client authentication using certificates

**Comment by AlexPikalov** [comment]
@harrydevnull Sounds reasonable. It would be great to have Rust native support of SSL as well.

**Comment by AlexPikalov** [comment]
There is a feature that allows using rust-tls. #321 
So, closing this issue
