### ISSUE TITLE
Is it possible to support scylladb?

### ISSUE THREAD

**Issue by crazyjin** [AlexPikalov/cdrs#138]
Scylla db is a very attractive Apache Cassandra implementation. When I run example/simple to connect to my scylladb  I got the following error:
```shell
thread 'main' panicked at 'Unexpected Cassandra version [131]', /home/felix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/cdrs-1.0.0-beta.8/src/frame/mod.rs:136
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
It looks like cdrs does not support scylladb right now. Is it possible to support scylladb which following the same specification as Cassandra?

**Comment by AlexPikalov** [comment]
@crazyjin 
As far as I can see, the main problem here is that Scylla relies on Native protocol v3 (http://docs.scylladb.com/cassandra-compatibility/) while CDRS at the current moment supports 4-th version only. I'd like to see CDRS to provide multiversion support. I think I could take a look on it in next few days.
