### ISSUE TITLE
How to insert uuid and time?

### ISSUE THREAD

**Issue by TrionProg** [AlexPikalov/cdrs#152]
Hello. I try
```
let create_post_cql = "INSERT INTO posts
            (id, author, date, last_edit, message, previous, next)
            VALUES (?, ?, ?, ?, ?, NULL, NULL)";

        let cassandra_create_post_query = cassandra_session.prepare(create_post_cql.to_string(), true, true)?.
            get_body()?.into_prepared().unwrap();

let id=Uuid::new(UuidVersion::Random).unwrap();

        let date=UTC::now();

        let mut id_vec:Vec<u8>=Vec::with_capacity(16);
        for b in id.as_bytes(){
            id_vec.push(*b);
        }

        let values: Vec<Value> = vec![
            id_vec.into(),
            author.into(),
            date.to_string().into(),//YYYY-MM-DD
            date.to_string().into(),
            message.into()
        ];

        let execution_params = CassandraParams::new(CassandraConsistency::One)
            .values(values)
            .finalize();

        let executed = cassandra_session.execute(&cassandra_create_post_query.id, execution_params, false, false)?.get_body()?;
```

* But it sends 84 bytes instead 16
```
[Value { body: [0, 0, 0, 16, 0, 0, 0, 1, 176, 0, 0, 0, 1, 233, 0, 0, 0, 1, 50, 0, 0, 0, 1, 138, 0, 0, 0, 1, 186, 0, 0, 0, 1, 96, 0, 0, 0, 1, 79, 0, 0, 0, 1, 117, 0, 0, 0, 1, 168, 0, 0, 0, 1, 84, 0, 0, 0, 1, 78, 0, 0, 0, 1, 37, 0, 0, 0, 1, 197, 0, 0, 0, 1, 111, 0, 0, 0, 1, 110, 0, 0, 0, 1, 65], value_type: Normal(84) }, Value { body: [0, 0, 0, 14], value_type: Normal(4) }, Value { body: [50, 48, 49, 55, 45, 48, 53, 45, 49, 57, 32, 49, 52, 58, 48, 48, 58, 48, 52, 46, 49, 50, 51, 52, 55, 51, 54, 55, 50, 32, 85, 84, 67], value_type: Normal(33) }, Value { body: [50, 48, 49, 55, 45, 48, 53, 45, 49, 57, 32, 49, 52, 58, 48, 48, 58, 48, 52, 46, 49, 50, 51, 52, 55, 51, 54, 55, 50, 32, 85, 84, 67], value_type: Normal(33) }, Value { body: [104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100], value_type: Normal(11) }]
```

Error: `"Server error: CString { string: "UUID should be 16 or 0 bytes (84)" }"`

And where are problems with date.

* What will contain body then this function will be executed?
* Add this to examples! Seriously where are no examples with parameters for INSERT, `.execute` and `.query`

UPD. I found this way
```
let id_value=Value::new_normal(cdrs::types::value::Bytes::new( Vec::from(&id.as_bytes()[..]) ));//schreck, ужас, horror

        let values: Vec<Value> = vec![
            id_value,
            author.into(),
            date.to_string().into(),//How to convert time::instant or chrono::Date to 8 bytes?
            date.to_string().into(),
            message.into()
        ];
```

I think, you should add UUID -> Value, &[u8] -> Value. 
But How to send date? time::Instant or chromo::Date -> Vec with length 8 bytes?
I think, where must be simple serialization. Just data, no any additional information(bincode turns [..]  that has length 16 to 24 bytes(it stores length) . It's mean, this serialization should not be recursive, but it should use Serde, then UUID,time and others will work good.
See https://github.com/sfackler/rust-postgres/tree/master/postgres-shared/src/types for example if you need.

UPD2.
Okey, I never surrender.
This works.
```
pub type Date=chrono::DateTime<chrono::UTC>;

 fn uuid_to_value(id:&Uuid) -> Value {
        Value::new_normal(cdrs::types::value::Bytes::new( Vec::from(&id.as_bytes()[..]) ))
    }

    fn date_to_value(date:&Date) -> Value {
        let naive_date=date.naive_utc();
        let base=chrono::naive::date::NaiveDate::from_ymd(1970, 1, 1).and_hms(0, 0, 0);//like UNIX
        let milliseconds_cassandra = naive_date.signed_duration_since(base).num_milliseconds();

        milliseconds_cassandra.into()
    }

//----------
let values: Vec<Value> = vec![
            Self::uuid_to_value(&id),
            author.into(),
            Self::date_to_value(&date),
            Self::date_to_value(&date),
            message.into()
        ];
```
But seriously you need add serialization. Nowdays where are 5 Vecs of Vec<u8>, this is slow, uncomfortable etc.

**Comment by AlexPikalov** [comment]
@TrionProg 
In order to insert uuid you can directly convert it into `Value` as it's done in [examples](https://github.com/AlexPikalov/cdrs/blob/master/examples/all.rs#L863).

As for inserting date, date is a unisigned integer in fact (https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec#L850) and in current stage you have to convert your date into such integer and then into `Value`. I know it's not hand, so it makes sense to create a separate issues for that.

**Comment by AlexPikalov** [comment]
@TrionProg Completely agree with you. Data structures serialisation process is non ergonomic and needs improvements.

**Comment by TrionProg** [comment]
I know, but this is very hard to get integer value from Data type. See how much dots and slow operation like signed_duration_since. I took this way from postgres serializatior and adapted it.
Currently I use 4 DBs and I found the most confortable postgresql
```
let exists_result_rows=self.postgres_session.query(
            "SELECT EXISTS(SELECT 1 FROM users WHERE login=$1)",
            &[&login]
        )?;

        if exists_result_rows.len()>0 {
            let exists:bool=exists_result_rows.get(0).get(0);

            if exists {
                ...
            }
        }
```

This query will be formatted to Vec<u8> directly. I think, you should make by this way.

And look on way tcp_connection -> session in mongodb crate. Your way has (self) methods, their way (&self) and each struct is the wrapper around Arc<Inner>. I found this more confortable, because your way need to drag adresses to create any connection.  But postgres works by way like your, but It has just 1 function instead 3. I think, mongodb is better. But this is not serious problem if it may be called problem, just architecture looks ugly:
```
pub fn new(redis_users_client:&RedisClient, redis_global_client:&RedisClient, mongo_db:&MongoDatabase, cassandra_address:&str) -> Result<Self,Error> {//all are clients, but cassandra or postgres are adresses
        let redis_users = redis_users_client.get_collection()?;
        let redis_global = redis_global_client.get_collection()?;
        let cassandra_session = Self::connect_to_cassandra(cassandra_address)?;
        let postgres_session = Self::connect_to_postgres()?;
        let mongo_users = mongo_db.get_collection("users");
```

I have the question. Is it good that I store cdrs::Session all runtime, but I use it often?

**Comment by AlexPikalov** [comment]
1. As far as I know the way of composing queries you've provided is quite common. I know at least few crates leveraging this approach. So it might make sense to have the same functionality here.

2. I've got your point. It sounds reasonable, especially with your example.

3. I don't see any problems with that.

Thank you.
