### ISSUE TITLE
Panic when shutting cassandra down

### ISSUE THREAD

**Issue by bfrog** [AlexPikalov/cdrs#163]
Saw this today while restarting one of the two cassandra nodes I have CDRS cluster connected to.

```ERROR:cdrs::frame: Unexpected Cassandra version 0, either 4 or 132 is expected```

Not sure how it happened, but immediately after that the program panicked and quit.

**Comment by AlexPikalov** [comment]
@bfrog 

Which Cassandra version do you use in your cluster? Did you start session with any compression?

Thanks

**Comment by bfrog** [comment]
3.0.9, no compression

**Comment by AlexPikalov** [comment]
TLS or plain TCP connection?

**Comment by bfrog** [comment]
Plain

**Comment by AlexPikalov** [comment]
Thanks, will try with 3.0.9.

**Comment by harrydevnull** [comment]
@bfrog  how many nodes were there to begin with and what was the replication factor ?

**Comment by bfrog** [comment]
2 and 2, I restarted one and got that error.

**Comment by AlexPikalov** [comment]
Probably we need to revise a mechanism of node invalidation in [cluster](https://github.com/AlexPikalov/cdrs/blob/master/src/cluster.rs#L131). Let me please take a look closer on the case you've described.
