### ISSUE TITLE
Crate version does not work with cargo.

### ISSUE THREAD

**Issue by s3bk** [AlexPikalov/cdrs#171]
"1.0.0-rc.3" does not appear to work correctly with cargo.
Thus one can't write

```
[dependencies]
cdrs = "*"
cdrs = "1.0"
cdrs = "1.0.0"
```

**Comment by s3bk** [comment]
Looks like docs.rs is to blame for showing the latest (unstable) version?

**Comment by AlexPikalov** [comment]
@s3bk 
Sorry for late reply. Both docs.rs and crates.io have the same behavior.
version `1.0.0` was published, so I hope there won't be such confusion in future.
