### ISSUE TITLE
Vec<u8> doesn't serialize properly

### ISSUE THREAD

**Issue by rrichardson** [AlexPikalov/cdrs#179]
You have to explicitly construct Bytes for it to work.  
To make that work within data structures,  Bytes needs to be Clone. 
I have made a PR for that here : 
https://github.com/AlexPikalov/cdrs/pull/178 

But we should figure out how to solve the broader problem that we need to treat Vec<u8> differently from Vec<T>

**Comment by AlexPikalov** [comment]
Good catch! Currently I'm trying to fix Travis CI. Once it's done I'll merge your PR and we could close this issue.
Thanks, @rrichardson

**Comment by AlexPikalov** [comment]
As a solution for differentiating blob from `Vec`, there is a PR with Blob type that has similar purposes as `Map`, `List`, `UDT`.

#181
