### ISSUE TITLE
Example for batches with parameters needed

### ISSUE THREAD

**Issue by maklemenz** [AlexPikalov/cdrs#195]
The [current example for batches](https://github.com/AlexPikalov/cdrs/blob/master/examples/batch_queries.rs#L39) does not show how values are passed to batch queries:
```
let batch_query = BatchQueryBuilder::new()
    .add_query_prepared(prepared.id.clone(), vec![])
    .add_query(run, vec![])
    .finalize()
    .unwrap();
```

That would be useful because the way how values are passed to non batched queries does not work for them:
```
let values: Vec<Value> = vec![a.into(),
                                  b.into(),
                                  c.into(),
                                  d.into()];
let execution_params = QueryParamsBuilder::new(Consistency::Any)
          .values(values).finalize();
batch_builder = batch_builder.add_query_prepared(prepared.id.clone(), values);



error[E0308]: mismatched types
  --> src/storing.rs:39:83
   |
39 |             batch_builder = batch_builder.add_query_prepared(prepared.id.clone(), values);
   |                                                                                   ^^^^^^ expected tuple, found struct `cdrs::types::value::Value`
   |
   = note: expected type `std::vec::Vec<(std::option::Option<cdrs::types::CString>, cdrs::types::value::Value)>`
              found type `std::vec::Vec<cdrs::types::value::Value>`
```

**Comment by AlexPikalov** [comment]
Hello @maklemenz
I agree this part is missed. I'll try to add such example for 1.x.x version ASAP. Meanwhile you can check out how process of passing values will look like in version 2.0.0 that I'm working on. https://github.com/AlexPikalov/cdrs/blob/v2.0.0/examples/version_2.rs#L55 I plan to implement something similar for query batching as well

**Comment by AlexPikalov** [comment]
As for upcoming version 2, example for batches with parameters could be found [here](https://github.com/AlexPikalov/cdrs/blob/v2.0.0/examples/prepare_batch_execute.rs#L75).

**Comment by kamek-pf** [comment]
@AlexPikalov Looks like the current methods for `BatchQueryBuilder` consume `self`, making it difficult to prepare big batches. I need to add queries to the builder using a loop, is there a way to do this currently ?

**Comment by AlexPikalov** [comment]
Hi @kamek-pf 
I'd need to analyse your use case. Please give me some time. I'll keep you updated in this topic
