### ISSUE TITLE
error while connecting to cassandra 2.2

### ISSUE THREAD

**Issue by harrydevnull** [AlexPikalov/cdrs#2]
i was trying to connect cassandra 2.2.4 on our network; but unfortunately rust panicked

 [source code](https://github.com/harrydevnull/cassandra-rust-test) 

below is the stacktrace which I got

`RUST_BACKTRACE=1 ./target/debug/cassandraaccess
Hello, world!
thread 'main' panicked at 'Unexpected Cassandra version [0]', /Users/hachandr/.cargo/registry/src/github.com-1ecc6299db9ec823/cdrs-0.2.0/src/frame/mod.rs:117
stack backtrace:
   1:        0x10e414d28 - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:        0x10e41730f - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:        0x10e416095 - std::panicking::default_hook::h0ac3811ec7cee78c
   4:        0x10e4165e6 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:        0x10e416484 - std::panicking::begin_panic::h6ed03353807cf54d
   6:        0x10e4163a2 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:        0x10e3fca1f - <cdrs::frame::Version as core::convert::From<collections::vec::Vec<u8>>>::from::h32cd9558c9a9ab7d
   8:        0x10e3faedb - cdrs::frame::parser::parse_frame::hd0b56c419b3c4827
   9:        0x10e3c76c1 - <cdrs::client::CDRS<T>>::start::hb87ef6d337d3d9e4
  10:        0x10e3cff4a - cassandraaccess::main::haeac6d31fbfd637f
  11:        0x10e4178ca - __rust_maybe_catch_panic
  12:        0x10e415bd6 - std::rt::lang_start::h538f8960e7644c80
  13:        0x10e3d0289 - main`

**Comment by AlexPikalov** [comment]
Thanks @harrydevnull for reporting.

Seems that it panics on https://github.com/AlexPikalov/cdrs/blob/master/src/frame/mod.rs#L117
Will try on cassandra 2.2.4.

Could you please provide an output of

```
cqlsh> show VERSION;
```

In my case it's
[cqlsh 5.0.1 | Cassandra 3.9 | CQL spec 3.4.2 | Native protocol v4]

Thank you

**Comment by harrydevnull** [comment]
5.0.1 | Cassandra 2.2.8 | CQL spec 3.3.1 | Native protocol v4]

**Comment by harrydevnull** [comment]
and one more server is speaking "tls"

**Comment by AlexPikalov** [comment]
Thank you.
I'll try to reproduce it on my local environment and probably come up with something more concrete.

**Comment by harrydevnull** [comment]
Btw if you were to use docker on local your will be able to switch between
versions of Cassandra easily.
My test code uses a rudimentary docker Cassandra image

My 2 cents..

**Comment by AlexPikalov** [comment]
@harrydevnull 
I've checked this issue on CDRS 0.7.0 + Cassandra SSL-encrypted client-node connection. For me it works fine.

It would be great if you could confirm the same from your end.

**Comment by AlexPikalov** [comment]
I'm closing this issue. If you have any issues with connection via SSL-encrypted connection to Cassandra 2.2 feel free to open new issue

**Comment by harrydevnull** [comment]
@AlexPikalov : I tried with tls and i started with a wrong certificate and so it was supposed to return error instead it was panicking.
{code}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: V4(xxx:64067), peer: V4(xxxx:9042), fd: 3 }, ssl: Ssl { state: "error", verify_result: X509VerifyError { code: 19, error: "self signed certificate in certificate chain" } } }, error: Ssl(ErrorStack([Error { code: 336134278, library: "SSL routines", function: "ssl3_get_server_certificate", reason: "certificate verify failed" }])) })', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:837
stack backtrace:
   1:        0x10f8e0dda - std::sys::imp::backtrace::tracing::imp::write::hd8952e96bd20f4b7
   2:        0x10f8e255f - std::panicking::default_hook::{{closure}}::hfd6ba86ea4dd6ba9
   3:        0x10f8e2207 - std::panicking::default_hook::h44ade8c78c995294
   4:        0x10f8e2a26 - std::panicking::rust_panic_with_hook::h3e771863e3ed8403
   5:        0x10f8e2874 - std::panicking::begin_panic::h0af46715c5e7593e
   6:        0x10f8e27e2 - std::panicking::begin_panic_fmt::h9509a584fa230ae8
   7:        0x10f8e2747 - rust_begin_unwind
   8:        0x10f9051f0 - core::panicking::panic_fmt::h5c28b8150c75bd71
   9:        0x10f879ee0 - core::result::unwrap_failed::h3e2777ab86f331c6
  10:        0x10f86e86c - <core::result::Result<T, E>>::unwrap::h8624c0fc54826597
  11:        0x10f8a645e - cdrs::transport_ssl::Transport::new::{{closure}}::h2f0231b2a03a7ed4
  12:        0x10f86df87 - <core::result::Result<T, E>>::map::ha45322ee1b6c6507
  13:        0x10f8a630d - cdrs::transport_ssl::Transport::new::h517c6ceb7fe0f49d
  14:        0x10f8598aa - cdrs_dart::main::h7080965054f13a02
  15:        0x10f8e389a - __rust_maybe_catch_panic
  16:        0x10f8e2dc6 - std::rt::lang_start::hefd96b70277e8a4a
  17:        0x10f85a5c9 - main
{code}

**Comment by AlexPikalov** [comment]
I'll probably need to revise unwraps.
Were you able to connect to your server with a correct certificate?
