### ISSUE TITLE
Fix coverage report

### ISSUE THREAD

**Issue by AlexPikalov** [AlexPikalov/cdrs#20]
As of now it shows that coverage is 100% which is not true.

It seems to be related to https://github.com/huonw/travis-cargo/issues/43

**Comment by harrydevnull** [comment]
What happened to this issue?

**Comment by harrydevnull** [comment]
@AlexPikalov : you can close this issue right?

**Comment by AlexPikalov** [comment]
@harrydevnull yes, seems to be fixed
