### ISSUE TITLE
How to run the examples?

### ISSUE THREAD

**Issue by maheshjena1** [AlexPikalov/cdrs#218]
Hi, 
I am a newbie for the rust. Can you please help me with how to run the example and test it?
Currently I am getting following error with "rustc":

$ rustc examples/prepare_batch_execute.rs 
error[E0463]: can't find crate for `cdrs`
 --> examples/prepare_batch_execute.rs:2:1
  |
2 | extern crate cdrs;
  | ^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.

Thanks, 
Mahesh

**Comment by maheshjena1** [comment]
I found way to add the external library using -L option, but still there is compilation issue:

$ cargo build
   Compiling version_check v0.1.4
   Compiling antidote v1.0.0
   Compiling cfg-if v0.1.4
   Compiling byteorder v0.5.3
   Compiling libc v0.2.43
   Compiling byteorder v1.2.4
   Compiling log v0.4.3
   Compiling uuid v0.6.5
   Compiling scheduled-thread-pool v0.2.0
   Compiling lz4-compress v0.1.0
   Compiling lazy_static v1.1.0
   Compiling rand v0.4.2
   Compiling time v0.1.40
   Compiling r2d2 v0.8.2
   Compiling snap v0.2.4
   Compiling cdrs v2.0.0-beta.1 (file:///home/jioadmin/Work/rust_testCode/cdrs)
    Finished dev [unoptimized + debuginfo] target(s) in 41.33s
jioadmin@jioadmin-HP-ProBook-440-G3:~/Work/rust_testCode/cdrs$ rustc -L target/debug examples/prepare_batch_execute.rs 
error[E0460]: found possibly newer version of crate `byteorder` which `cdrs` depends on
 --> examples/prepare_batch_execute.rs:2:1
  |
2 | extern crate cdrs;
  | ^^^^^^^^^^^^^^^^^^
  |
  = note: perhaps that crate needs to be recompiled?
  = note: the following crate versions were found:
          crate `byteorder`: /home/jioadmin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbyteorder-9f1eca6b0d25955b.rlib
          crate `cdrs`: /home/jioadmin/Work/rust_testCode/cdrs/target/debug/libcdrs.rlib

error: aborting due to previous error

For more information about this error, try `rustc --explain E0460`.

**Comment by AlexPikalov** [comment]
@maheshjena1 
Try `cargo run --example example_file_name`. For instance, `cargo run --example crud_operations` to run https://github.com/AlexPikalov/cdrs/blob/master/examples/crud_operations.rs

Feel free to re-open this issues if you're still facing this issue.

**Comment by maheshjena1** [comment]
thank you Alex, it indeed solved my issues.
