### ISSUE TITLE
latest uuid v0.7 conflict

### ISSUE THREAD

**Issue by kadfak** [AlexPikalov/cdrs#220]
I was using the latest uuid crate version (0.7) that appears to conflict with the version (0.6.5) CDRS uses.

I got an error while converting an `Uuid` into `Bytes`:
```rust
let uuid: Uuid = Uuid::new_v4();
let b: Bytes = uuid.into();
                    ^ the trait `std::convert::From<uuid::Uuid>` is not implemented for `cdrs::types::value::Bytes
```

Using the same version as CDRS resolved the issue for me.

**Comment by AlexPikalov** [comment]
Yeah, conversion from `Uuid` into `Bytes` is possible because `From` is implemented for a certain UUID version.
