### ISSUE TITLE
Unable to get transport in multi threaded application

### ISSUE THREAD

**Issue by apezel** [AlexPikalov/cdrs#230]
Hi, thank you for your great work on CDRS, it's amazing.
I'm encountering some problem with the latest beta in a multi threaded application : 
```
thread 'tokio-runtime-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: General("Unable to get transport")', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I'm using lazy_static to share the connection between threads : 
```rust
lazy_static! {
  pub static ref CASSANDRA: Arc<ClusterSession> = {
    new_connection()
  };
}

pub type ClusterSession = Session<RoundRobinSync<TcpConnectionPool<NoneAuthenticator>>>;

pub fn new_connection() -> Arc<ClusterSession> {
  let node = NodeTcpConfigBuilder::new(super::CONF.cassandra_host.as_str(), NoneAuthenticator {}).build();
  let cluster_config = ClusterTcpConfig(vec![node]);
  Arc::new(new_lz4(&cluster_config, RoundRobinSync::new()).expect("session should be created"))
}
```

inside the thread : 
```rust
do_something_with_cassandra(&CASSANDRA.clone())
```

The problem occurs specially if i'm running large batch inserts in parallel.

Am i doing something wrong or is it a bug with CDRS ?

**Comment by AlexPikalov** [comment]
The way you use it seems to be okay for me. Probably existing solution with `try_lock` misses some retry logic. Your proposal #231 seems to be completely valid solution, but I just want to ensure it doesn't lead to unexpected panics.

**Comment by AlexPikalov** [comment]
Thank you for creating the issue and providing a solution
