### ISSUE TITLE
'static lifetime for Session constructors

### ISSUE THREAD

**Issue by swizard0** [AlexPikalov/cdrs#234]
Hello, Alex!

As far I understand it the only way to create `Session` object is the constructors defined in [session.rs](https://github.com/AlexPikalov/cdrs/blob/master/src/cluster/session.rs) file: `new`, `new_snappy`, etc. 

The problem is that they all requires `ClusterTcpConfig<'static, A>` parameter, which means I can have only `&'static str` nodes addresses in `NodeTcpConfig`. Is there a way not to compile it into binary, for example, if I want to get my node address from a config file or something like that?

**Comment by AlexPikalov** [comment]
Hi @swizard0,

Thank you for your question.

I believe there is a way. I've played a bit with [crud_operations.rs](https://github.com/AlexPikalov/cdrs/blob/master/examples/crud_operations.rs). I've created a simplified config file `test.conf` with following content:

```
127.0.0.1:9042
```

And here is how I modified the code:

```rust
// uses go here
const CONFIG: &'static str = include_str!("./test.conf");

fn main () {
  let nodes: Vec<NodeTcpConfig<'static, NoneAuthenticator>> = CONFIG
    .split("\n")
    .map(|addr| NodeTcpConfigBuilder::new(addr, NoneAuthenticator {}).build())
    .collect();
  let cluster_config = ClusterTcpConfig(nodes);
  let no_compression: CurrentSession =
    new_session(&cluster_config, RoundRobin::new()).expect("session should be created");
// ...
}
```

Please let me know if it helps in your case.

**Comment by swizard0** [comment]
Indeed it does work, but that actually means that one should recompile the whole project after editing configuration file :)

If you might be interested I'd suggest to change the `addr` type in [config_tcp.rs](https://github.com/AlexPikalov/cdrs/blob/master/src/cluster/config_tcp.rs) from `&'a str` to `String` or maybe something more generic, for example, `T: AsRef<str>`. That shouldn't break your existing code and examples but should solve the problem with static-only parameters.

**Comment by AlexPikalov** [comment]
Yeah, indeed it makes sense. Feel free to submit a PR for that

**Comment by AlexPikalov** [comment]
@swizard0 

Another option that I've found is [`lazy_static!`](https://github.com/rust-lang-nursery/lazy-static.rs)

```rust
fn main() {
  lazy_static! {
    static ref config: String = read_to_string("./examples/test.conf").expect("should open config");
  }
  let nodes: Vec<NodeTcpConfig<'static, NoneAuthenticator>> = config
    .split("\n")
    .map(|addr| NodeTcpConfigBuilder::new(addr, NoneAuthenticator {}).build())
    .collect();
}
```
Please check it out. I'm pretty sure it will allow you to have a single binary working with different configs.

Hope it helps
