### ISSUE TITLE
CDRS driver fails to fetch data from Cassandra, if one or more of the columns has a "null" value.

### ISSUE THREAD

**Issue by MaenMax** [AlexPikalov/cdrs#241]
CDRS drives fails to fetch data from Cassandra, if one or more of the columns has a "null" value.

Code: 

fn select_struct(session: &CurrentSession) {
    let select_struct_cql = "SELECT *  FROM autopush.message_2018_10 where uaid='185afbf3d7a94fc6a577c20ffc62431d'";
    let rows = session
        .query(select_struct_cql)
        .expect("query")
        .get_body()
        .expect("get body")
        .into_rows()
        .expect("into rows");
    for row in rows {
        let my_row: RowStruct = RowStruct::try_from_row(row).expect("into RowStruct");
        println!("struct got: {:?}", my_row);
    }
}

Error details:
thread 'main' panicked at 'into RowStruct: General("Column or UDT property \'key\' is empty")', libcore/result.rs:1009:5

Table description:

CREATE TABLE autopush.message_2018_10 (
    uaid text,
    chidmessageid text,
    chids set<text>,
    current_timestamp decimal,
    data text,
    headers map<text, text>,
    timestamp int,
    ttl int,
    updateid text,
    PRIMARY KEY (uaid, chidmessageid)
) WITH CLUSTERING ORDER BY (chidmessageid ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';

Example of an entry  (Which has been failed) to be fetched into RowStructure:

 185afbf3d7a94fc6a577c20ffc62431d | 02:1545961471067:86ba2621-db55-4749-b38f-f8300133ae17 |                                     null |              null | K61oUoC5-EZRDHi2-R-EKBFO_aiV6iYFuAPAZ1zJmJ6F8mxdwaQ | {'crypto_key': 'dh=BM-rwWt2s4L6sFNuqJA6pzNE9zy-h1mbiUU_28hndA-IbyQJM3PLCk5787515X_9QX66IP34b8JM1HXQHzPb-A8', 'encoding': 'aesgcm', 'encryption': 'salt=bB7LtNdeLUXbtJTzM7715Q'} | 1545961468 |  300 | gAAAAABcJX_8_7OWPBENWF-w9BEDpX-O_rILoKS8PQir3c18ZNJN-tElzsrHUoA3uQs_RuJs7qNoSupz4LwUh6SxtkmsyWO7NnwVFyvwUH9mp-qmTl948hQl4fNToqArtq9d5P1oVo2yuqlHTFCf6uvkagt7pxr17kLuJnDgAOG5dvQ_E1qgkr6DYw7E5DpX3up1QLG-OI6e

**Comment by AlexPikalov** [comment]
Hi @MaenMax,

Please make sure in your `RowStruct` those fields that you expect to have `NULL` value have type `Option<T>`. If they are of non-optional type `T` and values are `NULL` there is no way to automatically convert such Cassandra row values into your `RowStruct`.

**Comment by MaenMax** [comment]
Hi Alex,

it is not my RowStruct 

This was defined in your example:

truct RowStruct {
  key: i32,
  user: User,
  map: HashMap<String, User>,
  list: Vec<User>,
}

I am not sure to understand. I think that whatever data the driver fetches from DB, it will un-marshal it into  
RowStruct. How do I specify column names ?

**Comment by MaenMax** [comment]
Oh I think I got what you meant. Let me try.

**Comment by MaenMax** [comment]
General("Column or UDT property \'key\' is empty")',

**Comment by MaenMax** [comment]
Hi Alex,

Any answer to this question ? 

Thanks

**Comment by AlexPikalov** [comment]
Hi @MaenMax ,

I'll try explain how unmarshaling works in CDRS in few words. First of all, each field in a Cassandra table is optional, meaning it can either contain an actual value or be empty (null or empty). Basically, to convert from a `Row` structure which is a set of bytes to some Rust struct such as `RowStruct` in your example there are two options:

1. to convert via implementing [`TryFromRow`](https://docs.rs/cdrs/2.0.0-beta.5/cdrs/types/trait.IntoRustByName.html) trait for your `RowStruct` either manually or to derive via `#[derive(TryFromRow)]` like in [my example](https://github.com/AlexPikalov/cdrs_decimal_example/blob/91175f89c3766d4c92e863edcd823e789dad7e90/src/main.rs#L32). Having that implemented you can proceed with [`RowStruct::try_from_row(row)`](https://github.com/AlexPikalov/cdrs_decimal_example/blob/91175f89c3766d4c92e863edcd823e789dad7e90/src/main.rs#L94). What does the driver do for you in this case is converting each field into `Option<T>` and then automatically unwrapping its value to `T`. If the `Option` has `None` value overall result is `Err(empty_column_error)`

2. You can do make manual field transformation [one by one](https://github.com/AlexPikalov/cdrs_decimal_example/blob/91175f89c3766d4c92e863edcd823e789dad7e90/src/main.rs#L111). In this case you use `get_by_name` method for those of fields that may be empty and the driver converts bytes to `Option<T>`. Also you can use `get_r_by_name` for fields where you don't expect empty values. This method converts bytes to `Option<T>` and tries to unwrap a value to `T`. Again,  if the `Option` has `None` value overall result is `Err(empty_column_error)`

Regarding appearing `Column or UDT property '{}' is empty` error it appears in two cases:

1. when you try to get a value of column which wasn't returned from a server as a response to your query (either it doesn't exist in table schema or you haven't included a column into your select query)

2. when you do `get_r_by_name` and a column contains an empty or null value.

PS please refer to my example that works with empty columns https://github.com/AlexPikalov/cdrs_decimal_example/blob/91175f89c3766d4c92e863edcd823e789dad7e90/src/main.rs

**Comment by MaenMax** [comment]
Thanks for your precious comments. I understood unmarshalling.
I was successful to read a row from router table. Defined my "RouterRowStruct" to be:

struct RouterRowStruct {
  uaid: String,
  connected_at: Decimal,
  current_month: String,
  last_connect: Decimal,
  node_id: String,
  record_version: i32,
  router_type: String,
}

**Comment by AlexPikalov** [comment]
Great! 👍
