### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by cnd** [AlexPikalov/cdrs#244]
As far as I understand to use `git` version with `[patch.crates-io]` it must be newer than in crates.io so possibly it will be much better if you will update version after right deploying to crates.
Correct me if I've mistaken with understanding.

**Comment by AlexPikalov** [comment]
Generally, version of a source from `[patch.crates-io]` should be the same as the one from `[dependencies]`. Thus no need to increment version right after publishing from that point of view.

Also you never know if any breaking changes/new features will be introduced during a development cycle. I would prefer to assign a version for a build accordingly to semver principles right before publish. After all there is an idea (#) to automate release process, so a CI script will parse all commit messages starting from a prev release (prev tag) and figure out what kind of increment should be applied - major, minor or patch version increment
