### ISSUE TITLE
Counters are documented as u64

### ISSUE THREAD

**Issue by lewisdiamond** [AlexPikalov/cdrs#251]
`type-mapping.md` specified counter -> u64, but when using u64 `try_from_row` fails. It should be documented as i64.

**Comment by AlexPikalov** [comment]
Hello @lewisdiamond ,

Thanks for submitting this issue.
You're right it should be `i64`. I've marked this as a documentation bug.

More precise with data marshaling/unmarshaling you can find in e2e tests https://github.com/AlexPikalov/cdrs/blob/master/tests/native_types.rs#L63
