### ISSUE TITLE
no function or associated item named `try_from_udt` found for type `uuid::Uuid` in the current scope

### ISSUE THREAD

**Issue by Thomas-QM** [AlexPikalov/cdrs#255]
hey! im back again with another bug (?)
uuid doesnt seem to work with ``#[derive(TryFromRow)]`` on what appears to be a perfectly sane struct:
```rust
#[derive(TryFromRow)]
pub struct SmallUser {
    pub id: UserId,
    pub email: String,
    pub verified: bool
}
```
where ``UserId`` is a type abbreviation for Uuid...

there appear to be no version conflicts, only one version of uuid is in Cargo.lock, but i get this:
```
error[E0599]: no function or associated item named `try_from_udt` found for type `uuid::Uuid` in the current scope
  --> src\user.rs:12:10
   |
12 | #[derive(TryFromRow)]
   |          ^^^^^^^^^^ function or associated item not found in `uuid::Uuid`
```

i have a lot of stuff in scope, i thought one of these shouldve worked:
```rust
pub use cdrs::consistency::Consistency;
pub use cdrs::frame::IntoBytes;
pub use cdrs::types::udt::UDT;
pub use cdrs::types::from_cdrs::FromCDRSByName;
pub use cdrs::types::{IntoRustByIndex, IntoRustByName};
pub use cdrs::types::value::{Bytes, Value};
pub use cdrs::types::prelude::*;
```

i only see timespec being used in the examples... is there something wrong with the uuid integration?

the same thing happens with ``Blob``

**Comment by AlexPikalov** [comment]
Hi @Thomas-QM ,

Please check this PR out https://github.com/AlexPikalov/cdrs/pull/256. I've extended tests for `Derive`. Now it has both `Blob` and `Uuid`. And they are passed. Please compare it with your own code. Hope it will help.

Full test file https://github.com/AlexPikalov/cdrs/blob/6bbe74a516e0e19635f827a1685f4acb9729312d/tests/derive_traits.rs

**Comment by Thomas-QM** [comment]
thanks! i found the error, its apparently the type abbreviation: ``pub type UserId = Uuid;``, and this works fine:

```rust
#[derive(TryFromRow)]
pub struct SmallUser {
    pub id: Uuid,
    pub email: String,
    pub verified: bool
}
```

maybe cdrs thinks UserId is a UDT, then goes out looking for the UDT implementation in the scope?

**Comment by AlexPikalov** [comment]
Yes, this is correct.

`TryFromRow` doesn't work with type aliasing such as `type X = Y`. During deriving `TryFromRow` `syn` crate returns a type of a field as a string and then it gets to https://github.com/AlexPikalov/cdrs-helpers-derive/blob/master/src/common.rs#L61 and matches with types that could be transformed to Cassandra values.

As you can see here https://github.com/AlexPikalov/cdrs-helpers-derive/blob/master/src/common.rs#L109 it falls to a default branch and then CDRS tries to work with that as if it was a UDT.
