### ISSUE TITLE
CDRS never included an example of using PasswordAuthenticator

### ISSUE THREAD

**Issue by MaenMax** [AlexPikalov/cdrs#263]
Can you please include an example in "examples" folder, which shows how to connect to Cassandra DB using  non-default credentials? 

For example, when I use :

pub type CurrentSession = Session <RoundRobin< TcpConnectionPool < PasswordAuthenticator > > >;

For authentication instead of: 

pub type CurrentSession = Session < RoundRobin< TcpConnectionPool < NoneAthenticator > > >;

I get this error:

"expected lifetime parameter"

Maen

**Comment by AlexPikalov** [comment]
Hi @MaenMax ,
Thanks for reporting this. I'm on it.

**Comment by MaenMax** [comment]
@AlexPikalov got u.

**Comment by AlexPikalov** [comment]
@MaenMax ,
Please check if having
```rust
type CurrentSession = Session<RoundRobin<TcpConnectionPool<PasswordAuthenticator<'static>>>>;
```
helps in your case.

From my end I'll try to refactor `PasswordAuthenticator` or to create a new authenticator (if it is a breaking change) that would be used as `org.apache.cassandra.auth.PasswordAuthenticator` strategy and it owns credentials and doesn't need to have lifetime specified.

**Comment by MaenMax** [comment]
Thanks. I modified the code.

**Comment by MaenMax** [comment]
It helped yes.

**Comment by AlexPikalov** [comment]
I've created new authenticator `StaticPasswordAuthenticator` that is easier to use. It's already in master
