### ISSUE TITLE
Lifetime issue with PasswordAuthenticator object

### ISSUE THREAD

**Issue by MaenMax** [AlexPikalov/cdrs#264]
When I try to pass Cassandra username  & Password, compiler complains about lifetime of the two variables (cass_user and cass_password).

let authenticator =  PasswordAuthenticator::new(& cass_user, & cass_password);

------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------

 let authenticator =  PasswordAuthenticator::new(& cass_user, & cass_password);                              
                                                               ^^^^^^^^^ borrowed value does not live long enough

let authenticator =  PasswordAuthenticator::new(& cass_user, & cass_password);                              
                                                                            ^^^^^^^^^^^^^ borrowed value does not live long enough

**Comment by MaenMax** [comment]
Since this code works:

let authenticator =  PasswordAuthenticator::new("cassandra", "cassandra");


I suspect that it is the same issue as #261 (Which was already fixed). Hope to fix this as well.

Thanks.

**Comment by MaenMax** [comment]
Sorry, closed it by mistake

**Comment by MaenMax** [comment]
@AlexPikalov  Any update on this issue? Thanks

**Comment by AlexPikalov** [comment]
@MaenMax 
I've created a new authenticator `StaticPasswordAuthenticator` that doesn't require static lifetime. It's already in master.
I'm going to publish it on crates.io today and bump the version to `2.1.0`
