### ISSUE TITLE
describe tables cql statement is not implemented?

### ISSUE THREAD

**Issue by MaenMax** [AlexPikalov/cdrs#268]
let describe_struct_cql = "DESCRIBE tables;";
    let rows = ddb
    .query(describe_struct_cql)
    .expect("query")
    .get_body()
    .expect("get body")
    .into_rows()
    .expect("into rows");

I tried to get the list of tables by using describe statement as above but I got this error:

thread '<unnamed>' panicked at 'query: Server(CDRSError { error_code: 8192, message: CString { string: "line 1:0 no viable alternative at input \'describe\' ([describe]...)" }, additional_info: Syntax(SimpleError) })', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Can you help me on how to get the list of tables in a particular keyspace?

Thanks

**Comment by AlexPikalov** [comment]
Hi @MaenMax ,
No, it's not implemented on CDRS level. Moreover, basing on the error you are receiving your Cassandra instance doesn't support it either. As you can see, it's a server error.

`describe table;` is a part command shell API (`cqlsh`) not a native CQL command.

Please check this answer on Stackoverflow https://stackoverflow.com/questions/38696316/how-to-list-all-cassandra-tables
