### ISSUE TITLE
CDRS driver does not support older Cassandra versions (2.x.x)

### ISSUE THREAD

**Issue by MaenMax** [AlexPikalov/cdrs#269]
I was not able to connect the driver to Cassandra DB  2.1.16

The error message is attached

![MicrosoftTeams-image](https://user-images.githubusercontent.com/18452136/60625128-c1e4cd80-9d9b-11e9-8935-82b5af63584d.png)

Could you please help to solve this issue for us ?

**Comment by AlexPikalov** [comment]
Hi @MaenMax 

Probably this version of Cassandra uses version 3 of binary protocol.
Please try to use CDRS with feature `v3`. Put it into your `Cargo.toml`:

```toml
cdrs = { version = "2" features=["v3"] default-features = false }
```

or

```toml
cdrs = { version = "2" features=["v3", "ssl"] default-features = false }
```
if you use SSL.

It should help

**Comment by MaenMax** [comment]
I will try and let you know. Thanks!

**Comment by AlexPikalov** [comment]
I'm closing this issue.
If you find any problems working with CDRS and version 3 Cassandra binary protocol please feel free to re-open this issue or create a new one.
Thanks.

**Comment by MaenMax** [comment]
Hi Alex,
Thanks for your comment. I recompiled my project with the modification you pointed to, but with no success. I got this error:

Thread '<unnamed>' panicked at 'query: Server(CDRSError { error_code: 8704, message: CString { string: "Keyspace system_schema does not exist" }, additional_info: Invalid(SimpleError) })', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


It looks like that CDRS driver expects some keyspace (system_schema) which did not exist in Cassandra versions 2.x.x. What's your thoughts on this? 

Thanks,
Maen

**Comment by AlexPikalov** [comment]
Seems like somewhere in your code you use something like `use system_schema;` and, in your version of Cassandra seerver, such keyspace doesn't exist.

**Comment by MaenMax** [comment]
Thanks for your insights ! That's true, I use that in my code. Because I need to get the list of tables in a particular keyspace.

```rust
let describe_struct_cql = "SELECT table_name FROM system_schema.tables WHERE keyspace_name = 'autopush'";
    let rows = ddb
    .query(describe_struct_cql)
    .expect("query")
    .get_body()
    .expect("get body")
    .into_rows()
    .expect("into rows");
```
Cassandra older versions do not have the default system_schema keyspace which will allow me to get the list of tables. Now, I don't have any idea  about how to do that in CDRS. At least, I know that in order to get the list of tables of a particular keyspace in Cassandra 2.1.x , there are two steps need to be done:


[1]   use <keyspace_name> ;
[2]   describe tables  ;


How to do that in CDRS? If it is not doable, I can use different driver just for this purpose (getting the list of tables), and the rest of operations, I can use CDRS.

Please advice on this.

**Comment by MaenMax** [comment]
Hi Alex,

I actually found the  Select statement which can retrieve the list of tables in Older Cassandra versions :

    let describe_struct_cql = "select  columnfamily_name  from system.schema_columnfamilies  where keyspace_name = 'autopush';";

It worked with me.

**Comment by AlexPikalov** [comment]
Hi @MaenMax ,
Great!
