### ISSUE TITLE
Compilation error with ssl feature

### ISSUE THREAD

**Issue by truthaman** [AlexPikalov/cdrs#271]
I have been trying to play with ssl feature, and facing compile issue due to typo on line 43 in src/cluster/config_ssl.rs
There are some extra characters  });  confusing compiler.
Also the rust-openssl v0.9.23 does not support OpenSSL 1.1.1 which prevents compilation on current Linux systems - could you please bump up version to 0.10 ?

**Comment by AlexPikalov** [comment]
Hi @truthaman,

Thank you for reporting this issue!
