### ISSUE TITLE
How to use TTL feature in CDRS?

### ISSUE THREAD

**Issue by MaenMax** [AlexPikalov/cdrs#283]
Hello Alex,

I would like to insert a record with TTL in Cassandra, so that it will get deleted after the TTL is consumed. Is there a way to do this in CDRS? 

I tried adding "USING TTL 60" at the end of the query but it did not work.

ine 1:145 missing EOF at \'USING\' (...? where uaid = ? [USING] TTL...

Is there a TTL setter at API level I can use? 

Thanks,
Maen

**Comment by AlexPikalov** [comment]
Looks like a problem with a query syntax. There is nothing CDRS could do for you in this situation. Please try to search in special Cassandra forums like Stackoverflow. For example [here](https://www.google.com/search?q=cassandra+missing+EOF+at+%27USING%27+site:stackoverflow.com&rlz=1C5AVSZ_enPL662PL662&sa=X&ved=2ahUKEwjChavLsLbkAhVRwcQBHdhYAmwQrQIoBDAAegQIBhAN&cshid=1567573231988298&biw=1280&bih=666).

TTL should be done during [insertion](https://docs.datastax.com/en/archived/cql/3.3/cql/cql_reference/cqlInsert.html), but `where` statement is usually used in `SELECt`. So the problem might be here.

**Comment by MaenMax** [comment]
Thanks for your insights Alex. It was a Syntax error
