### ISSUE TITLE
Examples Error: Non-frozen UDTs are Not Supported

### ISSUE THREAD

**Issue by wwwesleyyy** [AlexPikalov/cdrs#287]
Running the samples in `cdrs/examples/crud_operations.rs` against Scylla 3.0.10-0.20190815.b3bfd8c08 returns:

```
thread 'main' panicked at 'Table creation error: Server(CDRSError { error_code: 8704, 
message: CString { string: "Non-frozen User-Defined types are not supported, please 
use frozen<>" }, additional_info: Invalid(SimpleError) })', src/libcore/result.rs:999:5
```

**Comment by AlexPikalov** [comment]
Hi @wwwesleyyy,

I think we may want to add a separate e2e test step for Scylla to make sure we keep Scylla support.
This is something that we are missing in the CI
