### ISSUE TITLE
rustfmt configured but not used

### ISSUE THREAD

**Issue by ZakCodes** [AlexPikalov/cdrs#289]
I've tried running `cargo fmt` in the repository and about half of the files were modified.  
The biggest issue is with the number of spaces for indentation. Some files use 4 spaces and others use 2 spaces, the `rustfmt.toml` configures the project to use 2 spaces.

**Comment by AlexPikalov** [comment]
@ZakCodes Thanks for the issue.
It's true. It was disabled in times when `cargo fmt` required nightly version of Rust.
Now we can enable it.
