### ISSUE TITLE
new Uuid support

### ISSUE THREAD

**Issue by cnd** [AlexPikalov/cdrs#292]
starting from uuid `0.8.1` cdrs gives error:

the trait `std::convert::From<uuid::Uuid>` is not implemented for `cdrs::types::value::Bytes`

**Comment by AlexPikalov** [comment]
@cnd 

Thank you for creating this issue. If you are not working on a solution I'm going to pick this up

**Comment by cnd** [comment]
@AlexPikalov nothing for, I'm not working on solution :)
