### ISSUE TITLE
User guide SSL session

### ISSUE THREAD

**Issue by AERC18** [AlexPikalov/cdrs#297]
Hi @AlexPikalov, I found that the SSL session guide points to this file: [https://github.com/AlexPikalov/cdrs/blob/master/documentation/cdrs-session.md ](url) 
where is no actual documentation about creating SSL connection.

Going through the code I manage to do this: 

`
        type CurrentSession = Session<RoundRobin<SslConnectionPool<StaticPasswordAuthenticator>>>;

    fn create_session() -> CurrentSession {
    // ------------- Get the cassandra URI from CASSANDRA_URI env var ---------------------
    let cassandra_uri: String = env::var("CASSANDRA_URI").ok().unwrap();
    //let node = NodeTcpConfigBuilder::new("172.18.0.2:9042", NoneAuthenticator {}).build();
    // ------------- Authenticator -----------------------
    let user = "USER";
    let password = "PASSWORD";
    let auth = StaticPasswordAuthenticator::new(&user, &password);
    // ------------- SSL connector -----------------------
    let path = Path::new("CERT.pem");
    let mut ssl_connector_builder = SslConnector::builder(SslMethod::tls()).unwrap();
    ssl_connector_builder.set_ca_file(path).unwrap();
    let ssl_connector = ssl_connector_builder.build();
    let node = NodeSslConfigBuilder::new(&cassandra_uri, auth, ssl_connector).build();

    let cluster_ssl_config = ClusterSslConfig(vec![node]);
    let no_compression = new_ssl(&cluster_ssl_config, RoundRobin::new()).expect("session should be created");
    
    no_compression
    }

`

But this throws me a time out. 

Do you know, what is wrong with this? My idea is to create a PR updating the SSL Session guide with this running. 

Thank you.

**Comment by AlexPikalov** [comment]
Hi @AERC18 
I'd need to check the process of SSL connection
Will keep you updated in this issue thread

**Comment by AlexPikalov** [comment]
Closing this issue since https://github.com/AlexPikalov/cdrs/pull/309 got merged
