### ISSUE TITLE
TLS connections hang in 2.2.2 but seems to work in HEAD

### ISSUE THREAD

**Issue by dspadea** [AlexPikalov/cdrs#302]
SSL connections hang in 2.2.2, but it seems fixed in HEAD. Testing connecting to AWS Managed Cassandra using StaticPasswordAuthenticator and the AWS Root CA. The following code hangs every time in `new_ssl` with 2.2.2, but works fine if I clone this project and point cargo at my local copy at HEAD (currently 4e091897aa739b5e906411ef4ca8ca3d579390a6).

As it seems to be fixed in head, I assume you're aware of the issue, but there doesn't seem to be an issue against it, and I spent a long while yesterday thinking my code was broken somehow. This bug is more to save others some time.

```

    let authenticator = StaticPasswordAuthenticator::new(&user, &password);

    let mut ssl_builder = SslConnector::builder(SslMethod::tls()).unwrap();

    match ssl_builder.set_ca_file("AmazonRootCA1.pem") {
        Ok(()) => println!("Set ca cert file"),
        Err(e) => {println!("{:#?}", e);}
    };

    let ssl_connector = ssl_builder.build();


    let node = NodeSslConfigBuilder::new(addr, authenticator, ssl_connector)
        .connection_timeout(Duration::from_secs(5))
        .max_size(1)
        .min_idle(Some(1))
        .build();
    let cluster_config = ClusterSslConfig(vec![node]);

    println!("Connecting to cassandra at {}...", addr);
    let cassandra =
        new_ssl(&cluster_config, SingleNode::new()).expect("Error connecting to database");

```

**Comment by AlexPikalov** [comment]
@dspadea 
Thank you for submitting the issue. This is definitely a subject for investigation. Even if it's fixed it was done unintentionally.
I need to investigate it.

**Comment by AlexPikalov** [comment]
@dspadea 
I've published 2.2.3. I must contain the fix

**Comment by dspadea** [comment]
Verified! Looks like it's connecting now! Thank you for your speedy response!

**Comment by AlexPikalov** [comment]
You're very welcome
