### ISSUE TITLE
How to query UUID with query_values!

### ISSUE THREAD

**Issue by Jasperav** [AlexPikalov/cdrs#306]
When I try to query my data which have the PK of type UUID, I get this runtime error:

> UUID should be 16 or 0 bytes

With this code:

```
let query = "select * from schem.users where id= ?";
let values = query_values!("70e98076-b3e3-44be-a6c8-434ee27fbb6d");
let response_body = db_session.query_with_values(query, values).unwrap();
```

How can I query my data with type UUID?

**Comment by AlexPikalov** [comment]
Hi @Jasperav 
try to put parsed [`UUID`](https://docs.rs/uuid/0.8.1/uuid/) instead of a plain string.

```rust
let values = query_values!(
  Uuid::parse_str("70e98076-b3e3-44be-a6c8-434ee27fbb6d").unwrap()
);
```

**Comment by Jasperav** [comment]
Thanks this worked :)
