### ISSUE TITLE
Support load balancing and connection pooling 

### ISSUE THREAD

**Issue by harrydevnull** [AlexPikalov/cdrs#31]
cassandra client has to provide connection pooling options.For each Session, there should be one connection pool per connected host
details : http://docs.datastax.com/en/developer/java-driver/3.1/manual/pooling/

Similarly which node does the client connect to and what to specify what kind of load balancing policy have to be used.

details : https://teddyma.gitbooks.io/learncassandra/content/client/which_node_to_connect.html

**Comment by AlexPikalov** [comment]
@harrydevnull 
Thank you for adding this issue.

**Comment by AlexPikalov** [comment]
I've created a separate issue for load balancing #37
