### ISSUE TITLE
rustls alternative ssl feature

### ISSUE THREAD

**Issue by DoumanAsh** [AlexPikalov/cdrs#315]
This would be a good alternative on non-linux platforms

**Comment by AlexPikalov** [comment]
@DoumanAsh 

You are absolutely right. It would be great to start using native Rust rustls crate.
Do you think you'd like to give it a shot and prepare some PR? Let me know if you need any help with it.

**Comment by DoumanAsh** [comment]
Ok, do you want it as separate feature fom `ssl`?
Also, do you want ot allow both `ssl` and `rustls` to be present at the same time?

**Comment by AlexPikalov** [comment]
I think another feature like `native-ssl` would be a good point to start. Later on, when the implementation will be stabilised we ca deprecate existing `ssl` feature based on `open-ssl` crate in favour of `native-ssl` based on `rustls`.

To start the development you can easily check what is included into `ssl` feature and implement similar structures leveraging `rustls`.
