### ISSUE TITLE
Cannot use hostname instead of IP-address

### ISSUE THREAD

**Issue by Cronnay** [AlexPikalov/cdrs#322]
Hi there!

Maybe I have been reading the documentation poorly, in that case I apologize. Found similar issues, but they seem to be resolved.

If I run `let node = NodeTcpConfigBuilder::new("192.168.145.139:9042", NoneAuthenticator {}).build();` this will build and work fine. However, if I run:     
`let node = NodeTcpConfigBuilder::new("database:9042", NoneAuthenticator {}).build();` I get this message from the compiler:
`General("invalid IP address syntax")'`. 

Why can't I use hostname?

My toml
```toml
[dependencies]
cdrs = "2.3.0"
```

Cargo --version
`cargo 1.42.0 (86334295e 2020-01-31)`

**Comment by AlexPikalov** [comment]
Hi @Cronnay,
You are correct host resolving functionality is missed, unfortunatelly.

**Comment by AlexPikalov** [comment]
I'm going to check if simple `SocketAddr::from` before creating a `TcpStream` would help

**Comment by AlexPikalov** [comment]
Hi @Cronnay 
Could you please check if https://github.com/AlexPikalov/cdrs/pull/324? It must fix the problem you're facing.
If it works I'll be happy to publish the fix asap
