### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by ernestas-poskus** [AlexPikalov/cdrs#33]
Thank you this crate ! 

I have a suggestion regarding connection pool, de facto for pools in Rust is r2d2 https://github.com/sfackler/r2d2 have you considered it ?

**Comment by AlexPikalov** [comment]
@ernestas-poskus 
Yes, this is what I'm thinking about.

**Comment by AlexPikalov** [comment]
Connection pool had been implemented. So closing this question.
Please let me know if any further questions.
