### ISSUE TITLE
does IF feature already implemented while updating ?

### ISSUE THREAD

**Issue by ctopher7** [AlexPikalov/cdrs#334]
for example "UPDATE table SET column = 123 WHERE id = uuid IF EXISTS;"

i cant get it working with scylla, but when using cqlsh it works. Im aware scylla only implement this feature (lightweight transaction) on nightly build, and i already tried using cqlsh and it works.

**Comment by AlexPikalov** [comment]
the driver will send whatever query you need, interpretation and execution is completely on server
