### ISSUE TITLE
Rust panicking While executing example read_table_into_struct

### ISSUE THREAD

**Issue by harrydevnull** [AlexPikalov/cdrs#34]
while trying to execute the read_table_into_struct.rs the rust thread was panicking.

the rootcause of the issue is 
`emp_id` is an `int` on cassandra table and we are trying to deserialize to `i64`
conversion from `varint` to `i64` is seamless.

**Comment by harrydevnull** [comment]
#35

**Comment by AlexPikalov** [comment]
Merged. Thanks.
