### ISSUE TITLE
❗ NEW MAINTAINER IS WANTED❗

### ISSUE THREAD

**Issue by AlexPikalov** [AlexPikalov/cdrs#356]
I'm looking for a new maintainer for CDRS with possible full ownership transfer.
If you're interested please drop me an email
![email](https://dummyimage.com/400x150/000/fff.png&text=alex.pikalov.khar@gmail.com)

**Comment by krojew** [comment]
Some information - the async version is already present here: https://github.com/krojew/cdrs-tokio

**Comment by Jasperav** [comment]
@krojew I see you are actively developing the async fork! Make sure to also check out https://github.com/scylladb/scylla-rust-driver

**Comment by kawpii** [comment]
@AlexPikalov I think better to point users to official ScyllaDB Rust driver : https://github.com/scylladb/scylla-rust-driver which support CQL and has [better performance than cdrs](https://www.scylladb.com/2021/02/17/scylla-developer-hackathon-rust-driver/)

**Comment by Jasperav** [comment]
@kaushalyap  I made a PR about this: https://github.com/AlexPikalov/cdrs/pull/361
