### ISSUE TITLE
Support load balancing

### ISSUE THREAD

**Issue by AlexPikalov** [AlexPikalov/cdrs#37]
It's a separate issue for load balancing functionality

harrydevnull in #31:

Similarly which node does the client connect to and what to specify what kind of load balancing policy have to be used.

details : https://teddyma.gitbooks.io/learncassandra/content/client/which_node_to_connect.html

**Comment by harrydevnull** [comment]
And perhaps we might want to use 'mio' or 'Tokyo-rs' so it has better performance .

And we need to accept address of all the nodes

**Comment by AlexPikalov** [comment]
@harrydevnull 
Agree about addresses, however here I don't have a full understanding how it should look like for TLS connections.

As far as I understand there may be that only a part of nodes in a cluster requires TLS. In case if the other part of nodes does not, we have a mix of TLS/TCP connections. To handle it we'll need to change conditional compilation process in order to allow both type of connections in the same time. Which is not true at current moment because of some decision which were made.

**Comment by AlexPikalov** [comment]
BTW in case of TLS we'll need to provide SSL certificates for each node along with its address

**Comment by AlexPikalov** [comment]
Yet another thing.
When server events handling will be implemented we will have an ability to perform load balancing more effectively because server will inform us when some node goes down.

**Comment by harrydevnull** [comment]
1. I haven't come across a deployment where you have both TLS and Non-TLS nodes in same cluster
and client drivers (at least the ones i have come across)  go for all tls or none of nodes .
2. 

> BTW in case of TLS we'll need to provide SSL certificates for each node along with its address
yes we might need to revamp the api a little more like a say 
[ClusterBuilder](http://docs.datastax.com/en/drivers/java/2.1/com/datastax/driver/core/Cluster.Builder.html)
Java Driver and Python  drivers somewhat follow similar paradigms
and in case of tls all nodes would make use of the single certificate.

**Comment by AlexPikalov** [comment]
1. if it's so, it makes sense. I need to check if Cassandra actually prevents such kind of Clusters.
2. 👍

**Comment by harrydevnull** [comment]
Closing issue #102 and updating this ticket as it is closely related
right now the driver takes only a single node address as the input; in reality we should accept an array of hosts.
```
    let addr = "127.0.0.1:9042";
    let tcp_transport = TransportTcp::new(addr).unwrap();
```
to be replaced with 

```
    let nodes = "10.10.10.10:9042,10.10.10.11:9042,10.10.10.12:9042,10.10.10.13:9042"
    let tcp_transport = TransportTcp::new(nodes).unwrap();
```
