### ISSUE TITLE
Revise unwraps

### ISSUE THREAD

**Issue by AlexPikalov** [AlexPikalov/cdrs#45]
We need to rid of as many unwraps as possible to avoid panic.

**Comment by ernestas-poskus** [comment]
in addition find_by_name returns: Option<Result> which is a little cumbersome IMO, Option should be enough to cover both cases

**Comment by AlexPikalov** [comment]
@ernestas-poskus 
It sounds encouraging.

**Comment by AlexPikalov** [comment]
As for find_by_name. Do you mean this one https://github.com/AlexPikalov/cdrs/blob/master/src/types/mod.rs#L29?

If so, it appears for me reasonable to return `Option` in a same way as it is in [HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.get)

**Comment by harrydevnull** [comment]
We might want to revisit unreachables!() . That macro results in thread panicking. I have stumbled upon panicking at least thrice. So as a better practice it would be better to return errror::Error

**Comment by AlexPikalov** [comment]
@harrydevnull I agree that this approach should be revisited. They were used in those places which, as I assumed, won't be reached due to protocol specification. For instance, Version can be either `0x04` or `0x84`. Most probably in some cases this assumption was wrong.

I'll create a super-task to create tests for each module. There we could track progress.
