### ISSUE TITLE
Create AuthenticatorNone for servers which don't need authentication

### ISSUE THREAD

**Issue by AlexPikalov** [AlexPikalov/cdrs#46]
`CDRS` requires an `Authenticator` to be passed during initialisation. That is not suitable for those who work with Cassandra instance that does not need any authorisation. At current moment in order to initialise `CDRS` developers need to create their own authenticator and implement `Authenticator` trait for it.

So, I think we may provide such empty authenticator specially for such cases.

I propose to create `AuthenticatorNone` which returns [empty auth token and empty Cassandra class name](https://github.com/AlexPikalov/cdrs/blob/master/src/authenticators.rs#L3).

**Comment by ernestas-poskus** [comment]
AuthenticatorNone sound reasonable :+1:

**Comment by harrydevnull** [comment]
@ernestas-poskus @AlexPikalov is anyone working on it?  if not I can take this up
