### ISSUE TITLE
Reduce .clone()

### ISSUE THREAD

**Issue by ernestas-poskus** [AlexPikalov/cdrs#48]
Improve performance by reducing unnecessary .clone(). 

E.g.:

```rust
impl Frame {
    pub fn get_body(&self) -> ResponseBody {
        return ResponseBody::from(self.body.clone(), &self.opcode);
    }
```

double allocation

**Comment by AlexPikalov** [comment]
@ernestas-poskus 
Yes, absolutely agree. There maybe plenty of unnecessary clones in the code, so we need to look after them.

**Comment by AlexPikalov** [comment]
Using of clones was significantly reduced. Will create some metrics of memory usage.
