### ISSUE TITLE
Creation queries value binding API

### ISSUE THREAD

**Issue by ernestas-poskus** [AlexPikalov/cdrs#50]
At the moment it is cumbersome to bind values to INSERT, UPDATE queries.

I suggest something similar to PostgreSQL crate: https://github.com/sfackler/rust-postgres.

```rust
    conn.execute("INSERT INTO person (name, data) VALUES ($1, $2)",
                 &[&me.name, &me.data]).unwrap();
```

**Comment by AlexPikalov** [comment]
Definitely, this improvement can significantly simplify application development.

**Comment by AlexPikalov** [comment]
At the moment, value binding is possible via prepare/execute functions. [Example](https://github.com/AlexPikalov/cdrs/blob/master/tests/create_insert_table.rs#L125).
