### ISSUE TITLE
Question /Help

### ISSUE THREAD

**Issue by harrydevnull** [AlexPikalov/cdrs#51]
I had been trying to revamp api  using cassandra name as option but i was not able to get it to working.
it is because of the move 
```
error[E0505]: cannot move out of `self` because it is borrowed
   --> src/client.rs:102:50
    |
94  |             let cass_name =  self.authenticator.get_cassandra_name();
    |                              ------------------ borrow of `self.authenticator` occurs here
...
102 |                         return Ok(Session::start(self));
    |                                                  ^^^^ move out of `self` occurs here

error: aborting due to previous error

error: Could not compile `cars`.
```

i have uploaded the code in my fork 

https://github.com/harrydevnull/cdrs/pull/6

would you know what to do to get around it ?

**Comment by AlexPikalov** [comment]
@harrydevnull 
In general I like this idea.

At the moment I'm not able to make sure that it will work, but you can try either

```rust
return self.authenticator.get_cassandra_name()
    .ok_or_else(|| /*make an error here*/)
    .map(|auth| ...)
```

or using `match` as you're doing actually

```rust
match cass_name {
    Some(ref auth) => {...},
    None => {...}
```

**Comment by harrydevnull** [comment]
> match cass_name {
    Some(ref auth) => {...},
    None => {...}

i did try the second option it gave me another error 
```
  if authenticator.as_str() == auth {
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::cmp::PartialEq<&str>` is not implemented for `str`
```

**Comment by AlexPikalov** [comment]
In this case some reference `&` is missing when you're comparing. May be `f authenticator.as_str() == &auth` could help

**Comment by harrydevnull** [comment]
did actually try that as well ```f authenticator.as_str() == *auth``` but it is back to where i began

```
 --> src/client.rs:127:50
    |
94  |             let cass_name =  self.authenticator.get_cassandra_name();
    |                              ------------------ borrow of `self.authenticator` occurs here
...
127 |                         return Ok(Session::start(self));
    |                                                  ^^^^ move out of `self` occurs here
```

**Comment by AlexPikalov** [comment]
https://play.rust-lang.org/?gist=5186e1c51c0a349ef00b35178254523f&version=stable&backtrace=0

This pretty much illustrates your issue

**Comment by AlexPikalov** [comment]
It seems that it was solved.
