### ISSUE TITLE
it seems SSL stuff is not working anymore

### ISSUE THREAD

**Issue by harrydevnull** [AlexPikalov/cdrs#52]
it seems after SSL stuff is not compiling at all

**Comment by AlexPikalov** [comment]
I saw you're saying that #58 fixes this issue. What was an issue?

**Comment by AlexPikalov** [comment]
I see Debug is not derived.

**Comment by AlexPikalov** [comment]
I see. Debug could not be derived automatically. Good catch, thank you.

**Comment by AlexPikalov** [comment]
I've checked. Now it works.
