### ISSUE TITLE
Add possibility to connect to server via encrypted connection

### ISSUE THREAD

**Issue by AlexPikalov** [AlexPikalov/cdrs#6]
Since it's possible to configure a server to communicate with clients via encrypted connection we need to support this option as well.

**Comment by AlexPikalov** [comment]
Should be considered as a part of #29

**Comment by harrydevnull** [comment]
@AlexPikalov : out of curiosity what are you using to achieve this 
[_rusttls_](https://github.com/ctz/rustls/blob/master/examples/tlsclient.rs) ?
or [Tokio](https://tokio.rs/)

**Comment by AlexPikalov** [comment]
@harrydevnull 
It is openssl's ssl https://docs.rs/openssl/0.9.6/openssl/ssl/index.html
Only hardcore 😄
