### ISSUE TITLE
Adapt examples to ssl feature

### ISSUE THREAD

**Issue by AlexPikalov** [AlexPikalov/cdrs#63]
Reported in #61 

>When --all-features was used, the ssl transport
was provided via the transport_ssl module.
However, the examples were not prepared for this,
and cargo test --all-features would fail.
>
>As both transports are mutually exclusive, it
seems reasonable to just use the same module name
and make life easier for clients.

- [x] fix existing examples
- [x] add examples which would use ssl

**Comment by harrydevnull** [comment]
@AlexPikalov : earlier pr on examples is less ergonomic. as in why should a client bother to put config(not ssl)  for those who does n't have ssl setup. cassandra deployments mostly would run non-ssl (due to perf reasons) but because of org-wide  reasons (security) they might end up using ssl.

so in a nutshell what I was try to convey was the earlier examples were good !!! we have to find another way to incorporate bryson's change but leaving the examples in tact. perhaps use of enums or traits.
and one more it is better to rename ssl to tls

**Comment by AlexPikalov** [comment]
@harrydevnull : of course client should not put explicitly `#[cfg(not(feature="ssl"))]` into its real code if they don't need SSL. And, in fact, it's not needed.

At the moment for me it's hard to imagine how to implement it using enums. Could you please provide quick code snippet, so we could discuss?

**Comment by AlexPikalov** [comment]
In examples, `#[cfg(not(feature="ssl"))]` and `#[cfg(feature="ssl")]` should be considered as branches which a developer should refer to find a solution if he develops with SSL disabled and enabled respectively.

**Comment by AlexPikalov** [comment]
As an alternative modification, we could provide a single **trait** `Transport`, which CDRS would receive, from one hand. That could be an interface common to both TCP and TLS. After that we could have one `NetTransport` which would have feature specific constructor and `Read+Write` implementation.

So in a code, developer would has

```rust
use transport::NetTransport
```

**Comment by harrydevnull** [comment]
Yes that's what I have been trying to get at...
But I ran into couple of issues... I ll try to push to a branch so that you
can take a look...

**Comment by AlexPikalov** [comment]
@harrydevnull sure, go ahead. I'll take a look

**Comment by AlexPikalov** [comment]
@harrydevnull let me work on this change along with updating examples.

**Comment by harrydevnull** [comment]
sure !! go ahead

**Comment by harrydevnull** [comment]
@AlexPikalov : i have been trying out options I have pushed my code base to github
https://github.com/harrydevnull/cdrs/tree/some

**Comment by AlexPikalov** [comment]
@harrydevnull Awesome! After some minor formatting we could merge it. Just few hints:

1. https://github.com/harrydevnull/cdrs/blob/some/src/transport.rs#L20

```rust
TcpStream::connect(addr).map( | socket | Transport { tcp: socket })
``` 
2. https://github.com/harrydevnull/cdrs/blob/some/src/transport.rs#L43
```rust
TcpStream::connect(addr).map(|socket| Transport { tcp: socket })
```
3 https://github.com/harrydevnull/cdrs/blob/some/src/transport.rs#L14 would be better to put after `Transport` [declaration](https://github.com/harrydevnull/cdrs/blob/some/src/transport.rs#L37)

4. And of course we could replace needless `return xyz;` statements by simple `xyz` in accordance to [Clippy rule](https://github.com/Manishearth/rust-clippy/wiki#needless_return)


That is exactly what I was thinking about. 👍

**Comment by harrydevnull** [comment]
Nah it is not compiling yet 😩

**Comment by AlexPikalov** [comment]
I can take a look tomorrow.

**Comment by harrydevnull** [comment]
@AlexPikalov : you can close down this issue right?

**Comment by AlexPikalov** [comment]
@harrydevnull right. Closing.
