### ISSUE TITLE
prepared statment doesn't pass query parameter

### ISSUE THREAD

**Issue by harrydevnull** [AlexPikalov/cdrs#76]
I have been trying to get the prepared statement to work but it is not .

CQL  query 
------------
``` Insert into user_keyspace.users            (user_name ,password,gender,session_token, state,birth_year)    values  (?         ,  ?     ,     ?,            ?,     ?,  ?)```

Error
-------
```CDRSError { error_code: 8704, message: CString { string: "there were 6 markers(?) in CQL but 0 bound variables" }```

I have pushed the code to my branch 
https://github.com/harrydevnull/cdrs/tree/feature/more-integ-test

could you please take a look?

**Comment by AlexPikalov** [comment]
@harrydevnull I found a root cause. It's a serialization defect. I'll try to push the fix today.

**Comment by harrydevnull** [comment]
cool thank you

**Comment by AlexPikalov** [comment]
@harrydevnull Now you can try with latest master.
