### ISSUE TITLE
Consider dual-licensing (MIT or Apache)

### ISSUE THREAD

**Issue by grossws** [AlexPikalov/cdrs#84]
A lot of projects in Rust ecosystem use dual-licensing allowing downstream user to choose between MIT or Apache license which simplifies library use both for projects under GPLv2 (Apache License v2 is incompatible with it, so MIT is good choise) and others who wouldn't be forced to keep a copy of your full license in NOTICE file and could just put attribution there.

**Comment by AlexPikalov** [comment]
@grossws 
I'm not very good in all this stuff. To be able to proceed with dual licensing would it be enough if each of dependencies has either MIT or Apache license?

**Comment by tupshin** [comment]
You are really only asserting what license your own project's code is. And yes, it is quite reasonable for you to dual license yours as Apache/MIT even if some of your dependencies are only one or the other. I would recommend going this route.

**Comment by grossws** [comment]
All your deps seems to be compatible with both MIT and Apache License v2.0 (e.g. no GPL/AGPL, CC SA nor NC variants etc):
- byteorder - Unlicense/MIT
- log, uuid - MIT/Apache
- snap - 3-BSD
- lz4-compress - MIT
- r2d2 - MIT/Apache
- openssl use its own license which is Apache-like one

To relicense you should get permission from all major contributors (e.g. if only contribution is something trivial like typo fix -- you can go without permission from that person). 

You can take dual license header example from any project that use it (e. g. rust compiler itself). Also guide from something like https://github.com/kbknapp/clap-rs/issues/389 could be useful.

**Comment by AlexPikalov** [comment]
Thank you, guys, for your explanations.

@harrydevnull please let me know if you have any objections.
Thank you.

**Comment by AlexPikalov** [comment]
I suppose you don't mind

**Comment by harrydevnull** [comment]
You are the boss ☺️

**Comment by harrydevnull** [comment]
For the record !  I don't have any objections .

**Comment by AlexPikalov** [comment]
@harrydevnull thank you! 😄
